//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESHOP_Shop_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESHOP_Shop_Product()
        {
            this.SESHOP_Shop_Order_Item = new HashSet<SESHOP_Shop_Order_Item>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public double productPrice { get; set; }
        public string productImage { get; set; }
        public string productDesc { get; set; }
        public string productDimension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESHOP_Shop_Order_Item> SESHOP_Shop_Order_Item { get; set; }
    }
}
