//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESHOP_Shop_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESHOP_Shop_Order()
        {
            this.SESHOP_Shop_Order_Item = new HashSet<SESHOP_Shop_Order_Item>();
            this.SESHOP_Shop_Order_Payment = new HashSet<SESHOP_Shop_Order_Payment>();
        }
    
        public int orderID { get; set; }
        public Nullable<int> memberID1 { get; set; }
        public string orderStatus { get; set; }
    
        public virtual SESHOP_Shop_member SESHOP_Shop_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESHOP_Shop_Order_Item> SESHOP_Shop_Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESHOP_Shop_Order_Payment> SESHOP_Shop_Order_Payment { get; set; }
    }
}
