//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESHOP_Shop_Order_Item
    {
        public int orderItemID { get; set; }
        public Nullable<int> productID1 { get; set; }
        public int qty { get; set; }
        public Nullable<int> ShopOrderorderID { get; set; }
    
        public virtual SESHOP_Shop_Order SESHOP_Shop_Order { get; set; }
        public virtual SESHOP_Shop_Product SESHOP_Shop_Product { get; set; }
    }
}
