//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingModule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seshop : DbContext
    {
        public seshop()
            : base("name=seshop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SESHOP_Shop_member> SESHOP_Shop_member { get; set; }
        public virtual DbSet<SESHOP_Shop_Order> SESHOP_Shop_Order { get; set; }
        public virtual DbSet<SESHOP_Shop_Order_Item> SESHOP_Shop_Order_Item { get; set; }
        public virtual DbSet<SESHOP_Shop_Order_Payment> SESHOP_Shop_Order_Payment { get; set; }
        public virtual DbSet<SESHOP_Shop_Product> SESHOP_Shop_Product { get; set; }
    }
}
