//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESHOP_Shop_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESHOP_Shop_member()
        {
            this.SESHOP_Shop_Order = new HashSet<SESHOP_Shop_Order>();
        }
    
        public int memberID { get; set; }
        public string memberName { get; set; }
        public string memberTel { get; set; }
        public string memberEmail { get; set; }
        public string password { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESHOP_Shop_Order> SESHOP_Shop_Order { get; set; }
    }
}
